<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param int $limite
     * @return mixed
     */
    public function findAllUsers($limite = 10)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
                                SELECT u
                                FROM AppBundle:User u
                                ORDER BY u.lastLogin
                                ');
        $consulta->setMaxResults($limite);
        return $consulta->getArrayResult();
    }

//    /**
//     * @param $usuario
//     * @param DateTime $desde
//     * @param DateTime $hasta
//     * @return array
//     */
//    public function findChamadosByUser($usuario, DateTime $desde = '2016-01-01',DateTime $hasta)
//    {
//        $em = $this->getEntityManager();
//        $consulta = $em->createQuery('
//                                SELECT c
//                                FROM AppBundle:Chamado c
//                                WHERE c.nome = :usuario
//                                AND c.data > :desde
//                                AND c.data < :hasta
//                                ');
//        $consulta->setParameter('usuario', $usuario);
//        $consulta->setParameter('desde', $desde);
//        $consulta->setParameter('hasta', $hasta);
//        return $consulta->getResult();
//    }
}